### ISSUE TITLE
Deprecation warning `Bundler.with_clean_env`

### ISSUE THREAD

**Issue by randome** [gregorym/bump#105]
Running `rake bump:X` now shows the deprecation warning 

`[DEPRECATED] `Bundler.with_clean_env` has been deprecated in favor of `Bundler.with_unbundled_env`. If you instead want the environment before bundler was originally loaded, use `Bundler.with_original_env` (called at /.../gems/bump-0.9.0/lib/bump.rb:160)
`

**Comment by grosser** [comment]
can you make a PR to fix it ?
... ideally with `.respond_to?` so it still works with older bundlers

**Comment by randome** [comment]
Will try over the weekend 👍
