### ISSUE TITLE
Rakefile Configuration

### ISSUE THREAD

**Issue by mslinn** [gregorym/bump#111]
How could the `tag_prefix = ""` be made the default for a `Rakefile`? 

In other words, I want no prefix:
```
$ rake bump:patch
1.0.1
```

Instead of the default prefix `v`:
```
$ rake bump:patch
v1.0.1
```

**Comment by grosser** [comment]
use `TAG_PREFIX=` when bumping or set `ENV["TAG_PREFIX"]=""` in the `Rakefile`
