### ISSUE TITLE
How to define build version or metadata

### ISSUE THREAD

**Issue by rslhdyt** [gregorym/bump#118]
Semantic versioning supports a metadata version denoted by appending a plus sign. It declared in semver spec item no 10. 

https://semver.org/#spec-item-10

> 10. Build metadata MAY be denoted by appending a plus sign and a series of dot-separated identifiers immediately following the patch or pre-release version. Identifiers MUST comprise only ASCII alphanumerics and hyphens [0-9A-Za-z-]. Identifiers MUST NOT be empty. Build metadata MUST be ignored when determining version precedence. Thus two versions that differ only in the build metadata, have the same precedence. Examples: 1.0.0-alpha+001, 1.0.0+20130313144700, 1.0.0-beta+exp.sha.5114f85, 1.0.0+21AF26D3----117B344092BD.

In my case, I need to attach the build information like a short commit embedded into version information. I've tried to define a version like this in the VERSION file `1.0.0+a34wsfr`. But when I tried to run `bump current` it returned `1.0.0` instead of `1.0.0+a34wsfr`. Is it expected? And how to properly set the build version within this gem?

**Comment by grosser** [comment]
this is not supported, would need to make a PR to support it
as long as it's not too complicated 👍 for adding it

**Comment by rslhdyt** [comment]
Well noted @grosser, 

I'll try to submit a PR. How about setting an option like this?

```
bump minor --with-meta a34wsfr
```

and it will produce or add metadata to the version file?

1.0.0 -> 1.1.0+a34wsfr

**Comment by grosser** [comment]
yeah sounds good, maybe even just `--meta`

**Comment by rslhdyt** [comment]
After attempting to make a change to support build metadata, I discovered that the gemspec version attribute does not support build version metadata. If we define the build version metadata in the gemspec version as `1.0.0+as23d`, it will raise an error.

Another option is to ignore the metadata in the gemspec file. However, I understand that this may be too much to consider at the moment.

Thank you

**Comment by grosser** [comment]
FYI gemspec supports some kind of suffix like alpha1 etc, not sure what the validation on that is though ... and it's not the same as what you want with metadata
