### ISSUE TITLE
should not bundle unless I'm working on a gem

### ISSUE THREAD

**Issue by grosser** [gregorym/bump#68]
the only way the .lock would change is if I work on a gem that has a .gemspec ... right ?
... so ok to add that "look for gemspec" logic ?

@gregorym

**Comment by gregorym** [comment]
what's the behavior if we run `bundle` and a .gemspec doesn't exist?

**Comment by grosser** [comment]
I want it to not run bundle ... because it does not matter / should not matter

**Comment by splattael** [comment]
Good idea 👍
