### ISSUE TITLE
git tags missing for releases

### ISSUE THREAD

**Issue by glensc** [gregorym/bump#85]
- https://github.com/gregorym/bump/releases

also changelog missing.

by ci broke recently:
```
$ gem install --bindir=/usr/local/bin bump
ERROR:  Error installing bump:
	bump requires Ruby version >= 2.2.0.
ERROR: Job failed: exit code 1
```

can't even find to what version i should lock to

**Comment by grosser** [comment]
https://rubygems.org/gems/bump/versions/0.6.1

**Comment by grosser** [comment]
@gregorym are you not using bump to bump bump ? :D

**Comment by grosser** [comment]
... or missing the `rake release`

**Comment by gregorym** [comment]
Of course I do. However I just realized I was not using the `--tag` option... Maybe we should consider tagging by default. I don't need any downside in doing it.

**Comment by grosser** [comment]
`rake release` adds tags and might fail if it is already tagged

**Comment by gregorym** [comment]
I've created the missing tags. It shouldn't happen moving forward :)

**Comment by glensc** [comment]
you messed up one tag: `c4b6cf7` :)

![image](https://user-images.githubusercontent.com/199095/49703236-596dad80-fc0b-11e8-9545-64e8c1fdd507.png)

**Comment by gregorym** [comment]
THis one is too old, it does not count ;p

**Comment by glensc** [comment]
well. it's just 0.1.1 mistagged, hash and tag name mixed when creating tag. easy fix.
