### ISSUE TITLE
It would be useful to have next_version accessible as a public method

### ISSUE THREAD

**Issue by ysv** [gregorym/bump#86]
Here is our CI [script](https://github.com/rubykube/peatio/blob/571ac4bb685bff3eccdbfe82f66e9650a030f2d7/lib/tasks/release.rake#L30) and we need to use send because there is no ability to get next version without tagging

My suggestion is to move next_version method to public

I will submit PR for this change

**Comment by grosser** [comment]
yeah sounds good to me 👍 

maybe best to have it on `Bump` with `def next_version(bump, current = Bump::Bump.current)`
so using `Bump.next_version` is clean and intuitive ... also add a tiny snipped to the readme plz :)
