### ISSUE TITLE
After a gem bump, bundler should be run to update the Gemfile.lock

### ISSUE THREAD

**Issue by amalagaura** [gregorym/bump#91]
bundle will update the gemfile.lock with the new version, otherwise after we publish the gem we have local changes

**Comment by amalagaura** [comment]
I love this tool, but I am unable to use it because after a bump I have to push another commit which messes up the tagging.

**Comment by grosser** [comment]
Bump already has code to auto-bundle ... Bundle open the gen and sprinkle a
few puts to see where it is going wrong

**Comment by amalagaura** [comment]
I screwed up. Sorry for opening this issue.
