### ISSUE TITLE
Changelog without commit or a way to add Changelog message in between.

### ISSUE THREAD

**Issue by hidroo** [gregorym/bump#98]
Hello is there a way to separate the bump in two commands?

The first command to:

1. bump the version in the version.rb
2. add the version to Changelog.md
3. bundle update

I then want to go in and write my information in Changelog.md

Then I want to commit with the automatic message and tag the commit.

**Comment by grosser** [comment]
My workflow is usually:
- `rake bump:patch`
- edit Changelog
- git commit --amend --no-edit

does that work ?

**Comment by grosser** [comment]
... alternatively get the changelog ready before bumping and then bump

**Comment by hidroo** [comment]
No, because the tag is not there after the ammend

**Comment by grosser** [comment]
bump does not tag unless `tag_by_default` is set, usually that's done by `rake release`

**Comment by hidroo** [comment]
I do
`bump patch —tag —changelog`

The commit is tagged.

Then I edit the changelog and do

`git add changelog`
`got commit —amend —no-edit`

**Comment by grosser** [comment]
we could add a `bump tag` that just tags the current commit and then your workflow could be:
 - bump path --changelog
 - amend
 - bump tag

**Comment by hidroo** [comment]
Yes this could work. To tag the current commit with the current tag.

I do not know how that works.

**Comment by grosser** [comment]
just needs to run `git tag #{current_version}` or so ... see bump/bump.rb
for the bits you need
then add new method into bin/bump and it should kinda work
